


/*
	****************************************************************************************
	Filename   :    WidgetSet.c
	Description:    WidgetSet
			
	Generated by Musa ÇUFALCI 2019
	Copyright (c) Musa ÇUFALCI All rights reserved.
	*****************************************************************************************
*/


/*-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
A U T H O R I D E N T I T Y
-----------------------------------------------------------------------------
-------------------------------- --------------------------------------------
Musa  ÇUFALCI
-----------------------------------------------------------------------------
R E V I S I O N H I S T O R Y
-----------------------------------------------------------------------------
Date Author Modification Description
Type
---------- ------ ------------- ---------------------------------------------
2019 MK Added First creating after project editing
-----------------------------------------------------------------------------
*/




/*******************************************************************************
********************************************************************************
*
* This file was generated automatically by Embedded Wizard Studio.
*
* Please do not make any modifications of this file! The modifications are lost
* when the file is generated again by Embedded Wizard Studio!
*
* The template of this heading text can be found in the file 'head.ewt' in the
* directory 'Platforms' of your Embedded Wizard installation directory. If you
* wish to adapt this text, please copy the template file 'head.ewt' into your
* project directory and edit the copy only. Please avoid any modifications of
* the original template file!
*
* Version  : 9.20
* Profile  : STM32F746
* Platform : STM.STM32.RGB565
*
*******************************************************************************/



#include "ewlocale.h"
#include "WidgetSet.h"

/* Embedded Wizard */
